### PR TITLE
Feature/fpv 69

### PR DESCRIPTION
**Pull request by kikani-parth**
Implemented vote casting logic:
- Extracts userId from JWT 
- The app then sends a PATCH req to server with the payload as userId and candidateId.
- On a success response from the server, a farewell message is shown

### CODE REVIEW

**Comment by phamduylong** [comment]
I suggest we log user out of the app after a timeout as well, and navigate back to the login page.

**Comment by phamduylong** [comment]
Let's make it a bit clearer: I expect the user to be logged out (sent a log out request to the server). The navigation then can happen (countdown or not, just let the user know somehow). Then a new user can come and use the machine.

**Review by phamduylong — APPROVED** [review]
BAD

**Review by jaakkoiot — APPROVED** [review]
This is a great change -> the user gets logged out after voting with a clear message. Works in device too.

**Review by phamduylong — CHANGES_REQUESTED** [review]
Change

**Review by kendrick-807 — APPROVED** [review]

**Review by phamduylong — APPROVED** [review]

**Pull request merged**
